title: Seite

icon: 📄

tabs:
  page:
    label: Inhalt
    icon: page
    columns:
      - width: 2/3
        sections:
          main:
            type: fields
            fields:
              intro:
                label: Intro
                type: text
              text:
                label: Text
                type: markdown

      - width: 1/3
        sections:
          pages: sections/pages
          files: sections/files

  settings:
    label: Einstellungen
    icon: settings
    sections:
      cover: sections/cover
      icons:
        type: fields
        fields:
          navIcon:
            label: Menü-Icon
            type: text
            icon: smile
            help: >
              Iconnamen können auf <a href="https://fontawesome.com/icons?d=gallery">fontawesome.com</a> gefunden werden
          navDescription:
            label: Menü-Beschreibung
            type: textarea
            buttons: false
