title: Seite
preset: page

fields:
  intro:
    label: Intro
    type: text
  text:
    label: Text
    type: markdown

sidebar:
  pages: sections/pages
  files: sections/files
  cover: sections/cover
  navMeta: sections/navMeta
