title: Seite

icon: 📄

tabs:
  page:
    label: Inhalt
    icon: page
    columns:
      - width: 2/3
        sections:
          main:
            type: fields
            fields:
              intro:
                label: Intro
                type: text
              text:
                label: Text
                type: markdown

      - width: 1/3
        sections:
          pages: sections/pages
          files: sections/files

  settings:
    label: Einstellungen
    icon: settings
    columns:
      - width: 2/3
        sections:
          cover: sections/cover
          icons: sections/meta-icons

      - width: 1/3
        sections:
          metaInfo:
            type: info
            headline: Hinweis
            text: >
              Die folgenden drei Felder beginnend mit „Meta“ sind nur für Suchmaschinenoptimierung relevant.
            theme: none
          meta: sections/meta
