title: Seite
preset: page

fields:
  intro:
    label: Intro
    type: text

  text:
    label: Text
    type: markdown

sidebar:
  pages:
    extends: sections/pages

  files:
    extends: sections/files

  cover:
    extends: sections/cover

  navMeta:
    extends: sections/navMeta