type: fields
fields:
  metaImage:
    label: Meta-Bild
    type: files
    query: page.files.filterBy('template', 'image')
    uploads: image
    multiple: false
  metaTitle:
    label: Meta-Titel
    type: text
    icon: title
    help: >
      Standardmäßig "<i>Seitentitel</i> – NABU Gera-Greiz e.V.".
  metaDescription:
    label: Meta-Beschreibung
    type: textarea
    buttons: false
