type: fields
fields:
  metaImage:
    label: Meta-Bild
    type: files
    # query: page.files.filterBy('template', 'image')
    query: page.images
    uploads:
      template: image
    multiple: false
  metaTitle:
    label: Meta-Titel
    type: text
    icon: title
    help: >
      Nur eingeben, wenn der automatisch generierte Titel für soziale Netzwerke zu lang sein sollte.
  metaDescription:
    label: Meta-Beschreibung
    type: textarea
    buttons: false
