#!/usr/bin/env php
<?php

$base = dirname(__DIR__);
require $base . '/vendor/autoload.php';

use Kirby\Cms\App as Kirby;
use KirbyExtended\SiteMeta;

$kirby = new Kirby([
    'roots' => [
        'index'    => $base . '/public',
        'base'     => $base,
        'site'     => $base . '/site',
        'storage'  => $storage = $base . '/storage',
        'content'  => $storage . '/content',
        'accounts' => $storage . '/accounts',
        'cache'    => $storage . '/cache',
        'logs'     => $storage . '/logs',
        'sessions' => $storage . '/sessions',
    ]
]);

/**
 * @param int $seconds Time in seconds
 * @return bool
 */
function increase_time_limit(int $seconds): bool
{
    return set_time_limit(max(
        ini_get('max_execution_time'), $seconds
    ));
}

increase_time_limit(180);
SiteMeta::sitemap();

exit(0);
