#!/usr/bin/env php
<?php

$base = dirname(__DIR__);
require $base . '/vendor/autoload.php';

use Kirby\Cms\App as Kirby;
use KirbyExtended\SiteMeta;

$kirby = new Kirby([
    'roots' => [
        'index'    => $base . '/public',
        'base'     => $base,
        'site'     => $base . '/site',
        'storage'  => $storage = $base . '/storage',
        'content'  => $storage . '/content',
        'accounts' => $storage . '/accounts',
        'cache'    => $storage . '/cache',
        'logs'     => $storage . '/logs',
        'sessions' => $storage . '/sessions',
    ]
]);

SiteMeta::sitemap();

exit(0);
