title: Seite

tabs:

  pages:
    label: Dashboard
    icon: dashboard
    columns:
      - width: 1/2
        sections:
          blog:
            type: pages
            headline: Aktuelles
            status: all
            parent: site.find("aktuelles")
            sortBy: date desc
            template: article
            info: "{{ page.date.toDate('%d.%m.%Y') }}"
            layout: cards
            image:
              back: white
              cover: true
            limit: 9

      - width: 1/2
        sections:
          listed:
            headline: Gelistete Seiten
            type: pages
            status: listed
            info: "/{{ page.slug }}"
          unlisted:
            headline: Ungelistete Seiten
            type: pages
            status: unlisted
            info: "/{{ page.slug }}"
          draft:
            headline: Entwürfe
            type: pages
            status: draft

  settings:
    label: Einstellungen
    icon: cog
    columns:
      - width: 2/3
        sections:
          settings:
            type: fields
            fields:
              partners:
                label: Partner
                type: files
                query: site.images.filterBy('template', 'partner')
                layout: cards
                size: tiny
                required: true
              footerColumns:
                label: "Fußzeile: Spalten"
                type: structure
                fields:
                  text:
                    label: Text
                    type: textarea

      - width: 1/3
        sections:
          settings2:
            type: fields
            fields:
              coverImage:
                label: Cover
                type: files
                query: site.images
                multiple: false
                layout: cards
                required: true
              author:
                label: Autor
                type: text
                icon: user
                required: true
          partnersImages:
            headline: Partnerbilder
            type: files
            template: partner
            min: 1
            sortable: false

  images: tabs/images