title: Seite

tabs:
  articles:
    label: Aktuelles
    icon: headline
    columns:
      - width: 1/2
        sections:
          articleDrafts:
            extends: sections/articles
            headline: Artikelentwürfe
            parent: kirby.page('aktuelles')
            status: draft
            layout: cards
            size: tiny
          unlistedArticles:
            extends: sections/articles
            headline: Ungelistete Artikel
            parent: kirby.page('aktuelles')
            status: unlisted

      - width: 1/2
        sections:
          listedArticles:
            extends: sections/articles
            headline: Gelistete Artikel
            parent: kirby.page('aktuelles')
            status: listed

  pages:
    label: Seiten
    icon: folder
    columns:
      - width: 1/2
        sections:
          pageDrafts:
            headline: Entwürfe
            type: pages
            status: draft
            create:
              - default
              - category
              - blog
            image: icon

      - width: 1/2
        sections:
          listedPages:
            headline: Gelistete Seiten
            type: pages
            status: listed
            info: "/{{ page.slug }}"
            image: icon
          unlistedPages:
            headline: Ungelistete Seiten
            type: pages
            status: unlisted
            info: "/{{ page.slug }}"
            image: icon

  settings:
    label: Einstellungen
    icon: settings
    columns:
      - width: 2/3
        sections:
          settings:
            type: fields
            fields:
              headline01:
                label: Navigation
                type: headline
              navigationTabs:
                label: Links (mobil)
                type: pages
              headline02:
                label: Seitenspalte
                type: headline
              sidebarLinks:
                label: Links
                type: structure
                fields:
                  linkPage:
                    label: Seite
                    type: pages
                    multiple: false
                  linkImage:
                    label: Bild
                    type: files
                    multiple: false
                    query: site.files.filterBy('template', 'image')
                    uploads: image
                    image:
                      back: white
                  linkLabel:
                    label: Titel
                    type: text
              sidebarText:
                label: Text
                type: textarea
              headline03:
                label: Fußzeile
                type: headline
              partners:
                label: Partnerbilder
                type: files
                query: site.files.filterBy('template', 'partner')
                uploads:
                  template: partner
                image:
                  back: white
                required: true
              footerColumns:
                label: Spalten
                type: structure
                fields:
                  text:
                    label: Text
                    type: textarea

      - width: 1/3
        sections:
          cover:
            type: fields
            fields:
              coverImage:
                label: Kopfzeilenbild
                type: files
                query: site.images
                multiple: false
                layout: cards
                image:
                  back: white
                  cover: true
                  ratio: 21/9
                required: true
              author:
                label: Autor
                type: text
                icon: user
                required: true

          meta:
            extends: sections/meta
            fields:
              metaImage:
                query: site.files.filterBy('template', 'image')
                required: true

  images: tabs/images
