title: Seite

tabs:
  pages:
    label: Dashboard
    icon: dashboard
    columns:
      - width: 1/2
        sections:
          blog:
            type: pages
            headline: Aktuelles
            parent: kirby.page('aktuelles')
            template: article
            status: all
            sortBy: date desc
            info: "{{ page.date.toDate('%d.%m.%Y') }}"
            layout: cards
            image:
              back: white
              cover: true
            limit: 9

      - width: 1/2
        sections:
          listed:
            headline: Gelistete Seiten
            type: pages
            status: listed
            info: "/{{ page.slug }}"
          unlisted:
            headline: Ungelistete Seiten
            type: pages
            status: unlisted
            info: "/{{ page.slug }}"
          draft:
            headline: Entwürfe
            type: pages
            status: draft

  settings:
    label: Einstellungen
    icon: settings
    columns:
      - width: 2/3
        sections:
          settings:
            type: fields
            fields:
              partners:
                label: Partnerbilder
                type: files
                uploads: partner
                query: site.files.filterBy('template', 'partner')
                image:
                  back: white
                required: true
              footerColumns:
                label: Fußzeilenspalten
                type: structure
                fields:
                  text:
                    label: Text
                    type: textarea

      - width: 1/3
        sections:
          cover:
            type: fields
            fields:
              coverImage:
                label: Kopfzeilenbild
                type: files
                query: site.images
                multiple: false
                layout: cards
                image:
                  back: white
                  cover: true
                  ratio: 21/9
                required: true
              author:
                label: Autor
                type: text
                icon: user
                required: true

          meta:
            extends: sections/meta
            fields:
              metaImage:
                query: site.files.filterBy('template', 'image')

  images: tabs/images
